### ISSUE TITLE
enable email notification on openedx-ginkgo version

### ISSUE THREAD

**Issue by ksripathi** [vlead/vlabs-openedx-platform#18]
This issue tracks the efforts required to enable the email notification on openedx ginkgo version

**Comment by kraghupathi** [comment]
@ksripathi : 
Enabled the email notifications on [alpha-openedx.vlabs.ac.in](https://alpha-openedx.vlabs.ac.in/).

**Comment by ksripathi** [comment]
@kraghupathi 

Links are receiving with localhost please fix it with necessary domain name

**Comment by kraghupathi** [comment]
@ksripathi   
Fixing above issue

**Comment by sivashankerN** [comment]
@kraghupathi 

There is one variable in 

> /edx/app/lms.env.json

 file. 

Variable name is `SITE_NAME`
change the value from `localhost` to `alpha-openedx.vlabs.ac.in`
and restart the services of edxapp

**Comment by kraghupathi** [comment]
@ksripathi :  
We have changed from `localhost` to `alpha-openedx.vlabs.ac.in`. Please check the email notifications after registration with link domain name is `alpha-openedx.vlabs.ac.in`.
