### ISSUE TITLE
Deploy OpenedX platform to production using ADS service

### ISSUE THREAD

**Issue by sivashankerN** [vlead/vlabs-openedx-platform#31]
Deploy OpenedX platform to production using ADS service

**Comment by sivashankerN** [comment]
Deployed OpenedX platform using ADS.  Successfully deployed but Instance type is t2.small which is not enough for edx platform. need to change intance type to bigger one

**Comment by sivashankerN** [comment]
Variables to be modified in both the files `/edx/app/edxapp/lms.env.json` and `/edx/app/edxapp/cms.env.json`

"SITE_NAME": "openedx.vlabs.ac.in"
"PLATFORM_NAME": "Virtual Labs"
 "DEFAULT_FROM_EMAIL": "registration@vlabs.ac.in"

**Comment by sivashankerN** [comment]
Deployed OpenedX platform using ADS after changing the Intance type to m3.large

Made changes in OVPL code, file path `ovpl/config/adapters/aws_config.py`

supported_amis section 
  {'os': 'UBUNTU', 'version': '16.04', 'id': 'ami-a6f4ebdc'},

available_instance_types  section
    {'ram': 8192, 'instance_type': 'm3.large'}

**Comment by ksripathi** [comment]
commit it : 6684df71c018a5bc8b0cd94c3b0bb0952f58febb

**Comment by ksripathi** [comment]
Deployed Openedx platform and Vlabs landing pages using ADS and tested couple of labs whether feedback, usage and other things are working as intend or not

Openedx platform : http://test-openedx.vlabs.ac.in
vlabs landing pages: http://beta.base1.vlabs.ac.in
