### ISSUE TITLE
Review documents of conversion of OVA into AWS AMI and Restoration steps 

### ISSUE THREAD

**Issue by vleadadmin** [vlead/vlabs-openedx-platform#6]
Review documents of conversion of OVA into AWS AMI and Restoration steps.
[Document of conversion from OVA to AMI](https://gitlab.com/vlead-systems/docs/blob/master/src/aws-docs/convert-ova-to-ami.org).

[Restoration of databases document](https://github.com/vlead/vlabs-openedx-platform/blob/develop/src/deployment/backup-and-restore.org)
[Reference for this restoration steps](https://github.com/openedx-vlead/port-labs-to-openedx/blob/master/src/platform-install-configure/backup.org)

**Comment by sivashankerN** [comment]
This  issue was created by me.

**Comment by sivashankerN** [comment]
Made some changes in the ["OVA to AMI" document](https://gitlab.com/vlead-systems/docs/blob/master/src/aws-docs/convert-ova-to-ami.org).

**Comment by sivashankerN** [comment]
Added little more information to backup and restoration steps. 

[Restoration of databases document](https://github.com/vlead/vlabs-openedx-platform/blob/develop/src/deployment/backup-and-restore.org)
